name = "class8_report"
uuid = "1705746e-6b8c-43b0-a925-d028ee787697"
authors = ["Myxogastria0808 <r.rstudio.c@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
