name = "class5_report"
uuid = "11b1bfdf-a1d9-424d-837c-64f0714e8898"
authors = ["Myxogastria0808 <r.rstudio.c@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
