name = "struct_mytutorial"
uuid = "a2f99a6a-33e0-4b48-b896-c5f807cf6e9d"
authors = ["Myxogastria0808 <r.rstudio.c@gmail.com>"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
